// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqqjjsorjmgftevhmnsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxcWpqc29yam1nZnRldmhtbnNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTgyMTEsImV4cCI6MjA3MjM5NDIxMX0.b5M_GZh8_kcM-hVrTWAiVf9G-Y4emPtKpm8ry7Trt8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});